import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/styles/styles.scss";
import Nav from "@/layout/navbar/Nav";
import Footer from "@/layout/footer/Footer";
import ProviderContainer from "@/ProviderContainer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <ProviderContainer>  {children}</ProviderContainer>
     
        <Footer></Footer>
      </body>
    </html>
  );
}
